### ISSUE TITLE
Support resizing the desktop of the remote container

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-remote-docker#14]
It would be nice of the user could click on a resize button in the webpage and select from a list of common resolutions.

**Comment by stefanoborini** [comment]
Fixed by #38  #36  #35 #34  #32

**Comment by kitchoi** [comment]
@stefanoborini Am I right that the above PRs provides the ability to set the resolution (size) on startup of a container by passing environment variables/setting docker image labels?  Is there a way to resize per container (even if a label is specified) and after start up?

**Comment by stefanoborini** [comment]
@kitchoi yes. no.
