### ISSUE TITLE
Scroll wheel not working for VNC applications

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote-docker#33]
Apparently the scroll wheel is not propagated as an event. I am unsure about the reasons, but I can guess it's one of the following:
- the browser intercepts the scroll and captures the event before it's dispatched to the VNC client (unlikely)
- the vnc client we are using is unaware of the scroll event and/or doesn't channel it through the vnc protocol.
- the vnc server is unaware/not forwarding to X windows the scroll event.
- the xwindows is incorrectly setup.

**Comment by stefanoborini** [comment]
It might be a problem of the application we were using. Other applications don't exhibit the same problem.

Closing, but @dpinte might have a different feedback.

**Comment by dpinte** [comment]
@stefanoborini I think it is fine closing. For reference: the scroll wheel works fine with Canopy Geo but not with VirtualCore in the 3D viewer.
