### ISSUE TITLE
Autorestart nginx is not necessary

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote-docker#5]
nginx is auto-started by supervisor as a service.  Subsequent autorestarts fail as nginx is already running and this pollutes the error log.

**Comment by stefanoborini** [comment]
I am puzzled by this. nginx should only be restarted if it dies for whatever reasons. Why is it trying to spawn a second one, if the first one is still alive? And if the first one is gone, why is the address in use? is it missing a SO_REUSEADDR somewhere?

**Comment by kitchoi** [comment]
The first time `nginx` is called, it exits with 0.  We can set `autorestart` to `unexpected` and set 0 as one of the expected `exitcodes`.

**Comment by stefanoborini** [comment]
Which leads me to the question: why is it exiting with 0? is it spawning as a daemon? In that case we should run it with `daemon off`

**Comment by kitchoi** [comment]
Apparently nginx is not meant to be run with daemon off in production.

**Comment by stefanoborini** [comment]
ok then, it's probaby supervisord that needs to be told it's a daemon and should not attempt to restart it further, but should instead just monitor the pid.

**Comment by stefanoborini** [comment]
From the supervisord docs

> Nondaemonizing of Subprocesses
> Programs meant to be run under supervisor should not daemonize themselves. Instead, they should 
> run in the foreground. They should not detach from the terminal from which they are started.

**Comment by kitchoi** [comment]
So supervisord is not the right place for starting nginx.
